-- Create validation_leads table for the $99 Validation Landing Page
CREATE TABLE IF NOT EXISTS public.validation_leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  company_name text,
  phone_number text,
  email text NOT NULL,
  file_url text,
  file_name text,
  subscribe_newsletter boolean DEFAULT false,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'processing', 'completed', 'cancelled')),
  stripe_session_id text,
  stripe_payment_status text,
  validation_type text,
  amount_paid numeric(10,2),
  notes text,
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.validation_leads ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (for the public landing page form)
CREATE POLICY "Allow anonymous inserts" ON public.validation_leads
  FOR INSERT TO anon WITH CHECK (true);

-- Allow service role full access
CREATE POLICY "Service role full access" ON public.validation_leads
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Create indexes for lookups
CREATE INDEX idx_validation_leads_email ON public.validation_leads(email);
CREATE INDEX idx_validation_leads_status ON public.validation_leads(status);
CREATE INDEX idx_validation_leads_stripe_session ON public.validation_leads(stripe_session_id);
